version: '3'
services:
  master:
    build: ./master
    ports:
      - 8080:8080
    volumes:
      - ./master/:/work
    command: ['python', 'app.py']
    links:
      - vrasp1
      - vrasp2
      - vrasp3
      - vrasp4
      - vrasp5
      - room
      - sensor

  vrasp1:
    build: ./rasp
    volumes:
      - ./rasp/:/work
    command: ['python', 'app.py']

  vrasp2:
    build: ./rasp
    volumes:
      - ./rasp:/work
    command: ['python', 'app.py']

  vrasp3:
    build: ./rasp
    volumes:
      - ./rasp:/work
    command: ['python', 'app.py']

  vrasp4:
    build: ./rasp
    volumes:
      - ./rasp:/work
    command: ['python', 'app.py']

  vrasp5:
    build: ./rasp
    volumes:
      - ./rasp:/work
    command: ['python', 'app.py']

  room:
    build: ./room
    volumes:
      - ./room/:/work
    command: ['python', '-m', 'app']
    links:
      - db

  sensor:
    build: ./sensor
    links:
      - db
    volumes:
      - ./sensor/:/work
    command: ['python', 'app.py']

  db:
    build: ./db
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
