version: '3'
services:
  master:
    build: ./master
    ports:
      - 8080:8080
    volumes:
      - ./master/:/work
    command: ['python', 'app.py']
    links:
      - rasp1
      - rasp2
      - room
      - sensor
      - sensor-db

  rasp1:
    build: ./rasp
    volumes:
      - ./rasp/:/work
    command: ['python', 'app.py']

  rasp2:
    build: ./rasp
    volumes:
      - ./rasp:/work
    command: ['python', 'app.py']

  room:
    build: ./room
    volumes:
      - ./room/:/work
    command: ['python', 'app.py']

  sensor:
    build: ./sensor
    volumes:
      - ./sensor/:/work
    command: ['python', 'app.py']

  sensor-db:
    build: ./sensor-db
    ports:
      - 3306:3306
    volumes:
      - ./sensor-db/db/data:/var/lib/mysql #永続化
      - ./sensor-db/db/init:/docker-entrypoint-initdb.d #初期db
    environment:
      - MYSQL_ROOT_PASSWORD=password
