version: '3'
services:
  master:
    build: ./master
    ports:
      - 8080:8080
    volumes:
      - ./master/:/work
      - ./front/dist:/work/public
    command: ['python', 'app.py']
    links:
      - rasp1
      - rasp2
      - room
      - sensor

  rasp1:
    build: ./rasp
    volumes:
      - ./rasp/:/work
    command: ['python', 'app.py']

  rasp2:
    build: ./rasp
    volumes:
      - ./rasp:/work
    command: ['python', 'app.py']

  room:
    build: ./room
    volumes:
      - ./room/:/work
    command: ['python', 'app.py']

  sensor:
    build: ./sensor
    links:
      - sensor-db
    volumes:
      - ./sensor/:/work
    command: ['python', 'app.py']

  sensor-db:
    build: ./sensor-db
    volumes:
      - sensor-db:/var/lib/mysql
      - ./sensor-db/db:/docker-entrypoint-initdb.d #初期db
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  sensor-db:
